version: '3.8'

services:
  api-database:
    image: postgres
    container_name: api-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laravel_docker
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    links:
      - api-database
    depends_on:
      - api-database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8088:80"
  api-server:
    container_name: api-server
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - api-database

volumes:
  pgadmin_data: